name: Deploy static content to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Upload the content of the 'public' directory
          name: public
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          artifact-name: public
